services:
  postgres:
    image: postgres:17
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - .database:/var/lib/postgresql/data

  matomo-db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: matomo
      MARIADB_DATABASE: matomo
      MARIADB_USER: matomo
      MARIADB_PASSWORD: matomo
    volumes:
      - .matomo-db:/var/lib/mysql

  matomo:
    image: matomo:5
    ports:
      - '8080:80'
    environment:
      MATOMO_DATABASE_HOST: matomo-db
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: matomo
      MATOMO_DATABASE_DBNAME: matomo
    volumes:
      - .matomo:/var/www/html
    depends_on:
      - matomo-db
