packages:
  - .
minimumReleaseAge: 14400
minimumReleaseAgeExclude:
  - next
  - '@next/*'
  - react
  - react-dom
  - '@arckit/*'
  - '@storybook/*'
  - '@babel/*'
  - chromatic
  - rollup
  - '@rollup/*'
  - '@smithy/*'
  - '@aws-sdk/*'
  - '@swc/*'
  - empathic
allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  sharp: false
  unrs-resolver: false
