packages:
  - .
allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

minimumReleaseAge: 14400
minimumReleaseAgeExclude:
  - next
  - '@next/*'
  - react
  - react-dom
