export * from './address';
export * from './client';
export * from './denomination-sociale';
export * from './email';
export * from './forme-juridique';
export * from './name';
export * from './phone';
export * from './siret';
export * from './tva-intracommunautaire';
